### ISSUE TITLE
Missing main attribute in Manifest

### ISSUE THREAD

**Issue by fbattet** [appaloosa-store/appaloosa_client#3]
When I try to launch the appaloosa client via the command line : 
`java -jar appaloosa-client-1.3 -t my-token --groups 'my-group' my-app.apk`

I have this error message in result : 
`no main manifest attribute, in appaloosa-client-1.3.jar`

**Comment by benoittgt** [comment]
Thanks for your message. We will take a look.

**Comment by fbattet** [comment]
Thank You.
For your information, I managed to use the command line.
I have: 
  - added the plugins maven-assembly-plugin, maven-jar-plugin
  - builded the jar with the maven task assembly:assembly
  - used the generated .jar : "appaloosa-client-1.3-shaded.jar"
