### ISSUE TITLE
Can't run appaloosa-client-1.3.jar

### ISSUE THREAD

**Issue by sskorupski** [appaloosa-store/appaloosa_client#4]
Hi,

I failed to run the appaloosa-client-1.3.jar client with following steps:
1. ``java -jar appaloosa-client-1.3 --groupNames everybody -t myToken myApk.apk`` 

=> ``Error: Unable to access jarfile appaloosa-client-1.3``
2. Then i changed to ``java -jar appaloosa-client-1.3.jar --groupNames everybody -t myToken myApk.apk`` 

=> ``No main manifest attribute, in jar``
3. Finally ``java -cp appaloosa-client-1.3.jar com.appaloosastore.client.Main --groupNames everybody -t myToken myApk.apk`` 

=> 
```
java.lang.NoClassDefFoundError: joptsimple/OptionParser
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

Did I miss something ?

**Comment by bickycheese** [comment]
Anybody?! _(Windows environment)_

```
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

When running it using Maven (mvn execute:java) I get:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.389 s
[INFO] Finished at: 2018-04-20T15:03:53+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project appaloosa-client: The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java are missing or invalid -> [Help 1]

[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException
```

**Comment by bickycheese** [comment]
I got it running using Maven:

`mvn exec:java -Dexec.mainClass="com.appaloosastore.client.Main" -DskipTests -Dgpg.skip -Dexec.args="-t [token] [apk]"`

But I'd like to run it from the _jar_ and **not** the _maven project_.

**Comment by jeremybdk** [comment]
If needed you can clone the project, run `mvn clean install` to build the client and run it with `java -jar target/appaloosa-client-1.3-shaded.jar`

**Comment by bickycheese** [comment]
@jeremybdk thanks, I didn't know to use the `*-shaded.jar`
